# -*- coding: utf-8 -*-
"""SentimentAnalysis usingBERT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Und9XiLKRld1ELczxS1Ht-no-c70kYsh
"""

from transformers import pipeline
st = f"What a great guy he is good and awesome."
seq = pipeline(task="text-classification", model='nlptown/bert-base-multilingual-uncased-sentiment')
print(f"Result: { seq(st) }")

! pip install transformers